#!/usr/bin/env python3

import os


def main():
    choice = int(input("Choice:"))

    if choice == 1:
        username = input("Username:")
        password = input("Password:")
        secret = input("Secret:")
        with open(f"{username}_{password}", "w") as f:
            f.write(secret)

    if choice == 2:
        username = input("Username:")
        password = input("Password:")
        if os.path.exists(f"{username}_{password}"):
            with open(f"{username}_{password}") as f:
                print("Secret:", f.read())

    if choice == 42:
        print("SUPER SECRET BACKDOOR")
        username = input("Username:")
        os.system(f"cat {username}_*")


if __name__ == "__main__":
    main()
